FROM node:latest

RUN mkdir /usr/poller

WORKDIR /usr/poller

COPY package*.json .

RUN npm install

COPY src src

COPY tsconfig.json .

RUN npx tsc

RUN mkdir /usr/poller/prisma

COPY ./prisma/schema.prisma ./prisma

RUN npx prisma generate

EXPOSE 9011

CMD ["node", "dist/poller.js"]