# Use postgres/example user/password credentials
version: '3.1'

services:

  # nuxt-btc:
  #   image: michaelmorningstar/nuxt-btc:latest
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DATABASE_URL=postgresql://myuser:mypassword@pg:5432/mydatabase
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully

  pg:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    image: michaelmorningstar/migrator:latest
    ports:
      - 9022:9022
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@pg:5432/mydatabase
    volumes:
      - migrator_data:/usr/migrator

  poller:
    image: michaelmorningstar/poller:latest
    ports:
     - 9011:9011
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@pg:5432/mydatabase
  

volumes:
  pg_data:
  migrator_data: